#flp_confgen
description:
  This metric observes the nodes incoming traffic
details:
  Sum bytes for incoming traffic per source and destination nodes
usage:
  Evaluate network incoming usage breakdown per source and destination nodes
tags:
  - ingress
  - bytes
  - nodes
encode:
  type: prom
  prom:
    metrics:
      - name: node_ingress_bytes_total
        type: counter
        valuekey: Bytes
        filter:
          key: FlowDirection
          value: "0"
        labels:
          - SrcK8S_HostName
          - DstK8S_HostName
visualization:
  type: grafana
  grafana:
    - expr: 'topk(5,rate(netobserv_node_ingress_bytes_total[1m]))'
      legendFormat: '{{pod}} : ({{SrcK8S_HostName}}) -> ({{DstK8S_HostName}})'
      type: graphPanel
      dashboard: netobserv
      title:
        Top 5 Ingress Bandwidth per source and destination nodes
